// User roles
const USER_ROLES = {
  ADMIN: 'ADMIN',
  PROPERTY_MANAGER: 'PROPERTY_MANAGER',
  PROPERTY_OWNER: 'PROPERTY_OWNER'
};

// Property status
const PROPERTY_STATUS = {
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  RENTED: 'RENTED'
};

// Payment frequency
const PAYMENT_FREQUENCY = {
  MONTHLY: 'MONTHLY',
  QUARTERLY: 'QUARTERLY',
  SEMI_ANNUALLY: 'SEMI_ANNUALLY',
  ANNUALLY: 'ANNUALLY'
};

// Maintenance request status
const MAINTENANCE_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

module.exports = {
  USER_ROLES,
  PROPERTY_STATUS,
  PAYMENT_FREQUENCY,
  MAINTENANCE_STATUS
};
